# Generated by Django 3.1.3 on 2022-04-12 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220411_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_game_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last game date'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='number_of_games',
            field=models.SmallIntegerField(default=0, verbose_name='number of games'),
        ),
    ]
