# Generated by Django 3.1.3 on 2022-04-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220412_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_connect_to_telegram',
            field=models.BooleanField(default=False, verbose_name='Connect telegram account'),
        ),
    ]
