# Generated by Django 3.1.3 on 2022-04-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_connect_telegram_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='in_game_now',
            field=models.SmallIntegerField(default=0, verbose_name='Playing now or no'),
        ),
    ]
